### ISSUE TITLE
fsck is not a suitable command to check and repair an XFS filesystem ,use xfs_repair instead

### ISSUE THREAD

**Issue by 27149chen** [kubernetes/utils#125]
In method `formatAndMount` in file utils/mount/mount_linux.go, command `fsck -a` is used to check and repair all kind of filesystems, including xfs.
But in fact `fsck` does nothing for xfs, we should use `xfs_repair` instead.

See the references:
https://linux.die.net/man/8/xfs_repair
https://linux.die.net/man/8/fsck.xfs

**Comment by 27149chen** [comment]
We fixed it in our code by wrapping the Mounter struct, but it is not convenient, so I wonder if you can accept a PR for that?

**Comment by 27149chen** [comment]
it is fixed and merged in #126

**Comment by liggitt** [comment]
/reopen

since #126 was reverted

**Comment by liggitt** [comment]
closing since the xfs discussion revealed this is not actually an issue

/close
