### ISSUE TITLE
[mount] Do not print logs using klog directly, use an abstract log interface instead

### ISSUE THREAD

**Issue by 27149chen** [kubernetes/utils#135]
I'm talking about the `mount` lib.
The lib is using klog to print the log message directly, it is ok in kubernetes and other projects which use klog too. But for projects which use different log tools (like logrus), since they may use different log format, it will be hard to maintain and collect logs.
So I'm asking if we can use an abstract log interface to print the log.

**Comment by BenTheElder** [comment]
Agree, there are only a handful of hits currently, bringing this up in #k8s-code-organization on slack ... 
https://github.com/kubernetes/utils/search?utf8=%E2%9C%93&q=klog&type=

**Comment by 27149chen** [comment]
@BenTheElder thanks. I want to contribute, do you know any examples in other projects I can refer to?
Currently I have two ideas:
1. Add a logger field to all Mounter structs, default to klog, but it is changeable.
2. Make a string channel that redirect the log to right logger.
What do you think? Do you have other thoughts?

**Comment by BenTheElder** [comment]
I'm not sure what the acceptable approach would be. there's a code organization working group that would be a good place to start. the mentioned channel is one way to get in touch.

**Comment by 27149chen** [comment]
ok, I will ask the current approvers first, @jingxu97 @saad-ali @jsafrane, what's your opinions?
