### ISSUE TITLE
klog version v2 is not available yet

### ISSUE THREAD

**Issue by zettop** [kubernetes/utils#159]
It seems utils is pointing to k8s.io/klog/v2, but this directory does not exist in any of the versions of klog. Please check https://github.com/kubernetes/klog.

This cause `dep ensure` to fail with an error

 master: Could not introduce k8s.io/utils@master, as it requires package k8s.io/klog/v2 from k8s.io/klog, but in version v2.0.0 that package is missing.

**Comment by dims** [comment]
@zettop which project are you trying to update to newer k8s.io/utils?

**Comment by akhilerm** [comment]
Facing the same issue. 
```
Solving failure: Could not introduce k8s.io/utils@master, as it requires package k8s.io/klog/v2 from k8s.io/klog, but in version v2.0.0 that package is missing.
```

Tried to update k8s dependencies to 1.17.3 using dep.

I think k/utils is always referring to master, and hence this issue.

**Comment by akhilerm** [comment]
I can see that klog /v2 is used in multiple places. https://github.com/kubernetes/utils/blob/614e4363e9c43ed6690291958959b83cee6b9452/mount/mount_helper_common.go#L23

But couldn't find that package in the `kubernetes/klog` repo.

**Comment by akhilerm** [comment]
nevermind, this works, Its a convention used in go mod

**Comment by Aitozi** [comment]
@akhilerm how doyou solve this problem?

**Comment by Aitozi** [comment]
does this problem caused by dep ? @akhilerm
