### ISSUE TITLE
Remove drive letter during formatAndMount causes subPath evalSymlink issue

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/utils#172]
In PR https://github.com/kubernetes/utils/pull/166, we remove driver letter during formatAndMount due to the issue of driver letter runout. Now, volume mount will create symlink from volumeId to a path. e.g., 
mklink testlink  \\?\Volume{2f230ace-0000-0000-0000-010000000000}\

However, in subPath setup, https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/subpath/subpath_windows.go#L53
filepath.EvalSymlinks(hostPath) 
will fail with error: too many links. 

We need to find another way to evaluate the symlink when driver letter is not assigned.

**Comment by andyzhangx** [comment]
actually I the author of that code `finalSubPath, err := filepath.EvalSymlinks(hostPath)`, can we skip this `too many links` directly in the code if `hostPath` starts with `\`, this should be bug in `filepath.EvalSymlinks`

**Comment by jingxu97** [comment]
@andyzhangx you mean skip this EvalSymlinks  check or if the error is "too many links", we ignore the error?

**Comment by jingxu97** [comment]
@andyzhangx but that means we don't check symlink for subpath in this case. Then it will open up the security issue that was fixed by this symlink check, I think.

**Comment by jingxu97** [comment]
> Is that windows specific code, or will that open a hole in Linux symlink checking?

This is mount_windows.go code. So the changes here will not affect linux symlink checking.

**Comment by networkimprov** [comment]
Re Go filepath.EvalSymlinks, see https://github.com/golang/go/issues/40180

It is probably not a good solution to any problem, except to show an administrator where a certain path leads *at this moment*.

**Comment by jingxu97** [comment]
/remove-lifecycle stale

We made a workaround to solve this, but still want to investigate more to find a better way..
