### ISSUE TITLE
[cinder-csi-driver] delete statefulset pod then new pod remounted failed with blkid returns invalid output

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/utils#174]
i deploy a statefulset with replicas one used cinder pvc ,then running
second,i delete the pod and the new replicas pod remount pvc but failed:

web-0 1/1 Running 0 4d23h 172.30.0.1 18.1.1.1
web-0 1/1 Terminating 0 4d23h 172.30.0.17 18.1.1.1
web-0 0/1 Terminating 0 4d23h 18.1.1.1
web-0 0/1 Pending 0 4s 18.1.1.1
web-0 0/1 ContainerCreating 0 4s 18.1.1.1

the web-0 pod logs :
Events:
Type Reason Age From Message

Normal Scheduled 2m8s default-scheduler Successfully assigned default/web-0 to 188.1.1.11
Normal SuccessfulAttachVolume 104s attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-c9947920-991c-41cf-b08e-648ad67b6eb4"
Warning FailedMount 24s (x8 over 95s) kubelet, 188.1.1.11 MountVolume.MountDevice failed for volume "pvc-c9947920-991c-41cf-b08e-648ad67b6eb4" : rpc error: code = Internal desc = failed to get disk format of disk /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: blkid returns invalid output: /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: UUID="27b52caf-ec56-489e-91e6-4f3d003b43c2" TYPE="ext4"
Warning FailedMount 5s kubelet, 188.1.1.11 Unable to attach or mount volumes: unmounted volumes=[www]

the ds node-plugin logs :
I0611 09:04:39.526996 1 mount_linux.go:405] Attempting to determine if disk "/dev/disk/by-id/virtio-c14a81a4-3d68-4288-9" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9])
I0611 09:04:39.544355 1 mount_linux.go:408] Output: "/dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: UUID="27b52caf-ec56-489e-91e6-4f3d003b43c2" TYPE="ext4"\n", err:
E0611 09:04:39.546005 1 utils.go:83] GRPC error: rpc error: code = Internal desc = failed to get disk format of disk /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: blkid returns invalid output: /dev/disk/by-id/virtio-c14a81a4-3d68-4288-9: UUID="27b52caf-ec56-489e-91e6-4f3d003b43c2" TYPE="ext4"

the k8s.io/utils/mount/mount_linux.go the function GetDiskFormat

the blkid command output error

1 mount_linux.go:407] dataOut: "/dev/disk/by-id/virtio-9fd0a671-3ebe-4dda-a: UUID=\"cce8468c-8f7e-4816-9ed0-81a83db4d7a1\" TYPE=\"ext4\"\n"

but the command blkid output is :
[root@paas-controller-1:/home/ubuntu]$ blkid -p -s TYPE -s PTTYPE -o export /dev/disk/by-id/virtio-9fd0a671-3ebe-4dda-a 
DEVNAME=/dev/disk/by-id/virtio-9fd0a671-3ebe-4dda-a
TYPE=ext4

**Comment by jianglingxia** [comment]
@jingxu97  @liggitt  can help see the issue   thanks all
the same with :https://github.com/kubernetes/cloud-provider-openstack/issues/1098

**Comment by phillc** [comment]
Hello, just throwing out there that I encountered this error, and it was because blkid provided by alpine linux does not support some of the flags that kubernetes/utils uses. I was able to add `RUN apk add --no-cache blkid` to my Dockerfile and it started working.
