### ISSUE TITLE
Issues with Clock

### ISSUE THREAD

**Issue by ash2k** [kubernetes/utils#196]
https://github.com/kubernetes/utils/blob/67b214c5f920060488eda08cd2b5c30597f2f1d7/clock/clock.go#L31-L37

1. `After(d time.Duration) <-chan time.Time` does not allow to stop the underlying timer to free resources if it's no longer needed. This can lead to memory leaks when a lot of long-lived timers pile up. It's a [well-known pitfall](https://medium.com/@oboturov/golang-time-after-is-not-garbage-collected-4cbc94740082). The fix is to remove the method and use the `Timer()` method instead.

2. `Tick(d time.Duration) <-chan time.Time` has the same issue as `After()`. This method should be replaced with [`NewTicker()`](https://github.com/kubernetes/apimachinery/blob/15c5dba13c59f42b25aba4e3a6b17061af770216/pkg/util/clock/clock.go#L39) from the sister package (which I added here https://github.com/kubernetes/kubernetes/pull/61976).

3. `Sleep(d time.Duration)` should take `context.Context` to allow for early interruption of sleep. This method is used e.g. in client-go to [sleep between request retries](https://github.com/kubernetes/client-go/blob/e9d996dae239d57f7d96af0c3cc19e3b6e2eaf83/rest/urlbackoff.go#L105-L107) and often there is a context to signal that the attempt should be aborted. Currently there is no way to interrupt this sleep.

**Comment by ash2k** [comment]
I'd like to replace https://github.com/kubernetes/kubernetes/pull/93709 with clock usage.

**Comment by liggitt** [comment]
Removing methods from the interface is not API compatible, and is not permitted for the utils library due to its wide use across versions and across projects.

Adding methods to surface the NewTimer and NewTicker methods provided by the `time` package and marking the `After` and `Tick` methods deprecated (but not removing them) could be reasonable.

> Sleep(d time.Duration) should take context.Context to allow for early interruption of sleep. This method is used e.g. in client-go to sleep between request retries and often there is a context to signal that the attempt should be aborted. Currently there is no way to interrupt this sleep.

These methods mirror the ones provided by the `time` package. There is no `Sleep(context.Context, time.Duration)` method, so I would not expect our clock fake to provide that.

**Comment by ash2k** [comment]
Thanks for responding. I agree adding + deprecating methods is a better way forward. This repository is different from all the other Kubernetes repositories that I've seen - it provides some compatibility guarantees. There is way more code that is using the unstable APIs (e.g. client-go) than these utils, so I'm curious why it's been made special.

Regarding `Sleep` - if the Clock does not have the method I'm suggesting then I see the following not mutually exclusive outcomes:
- (ok-ish) People use Clock's Timer + select on context to implement interruptible sleep. The existing Sleep method is not as useful as it could be.
- People use Clock's Sleep and the sleep is not interruptible where it should be. This is suboptimal as often the resources can be freed earlier and latency reduced if cancellation is respected.

> These methods mirror the ones provided by the `time` package. There is no `Sleep(context.Context, time.Duration)` method, so I would not expect our clock fake to provide that.

Yes, but it'd be very useful to have on the fake clock. According to the description, this repo is for "packages supplementing the Go standard libs" so hopefully it can still fit?

**Comment by liggitt** [comment]
> > These methods mirror the ones provided by the `time` package. There is no `Sleep(context.Context, time.Duration)` method, so I would not expect our clock fake to provide that.
> 
> Yes, but it'd be very useful to have on the fake clock. According to the description, this repo is for "packages supplementing the Go standard libs" so hopefully it can still fit?

The intent of the clock interface is to allow swapping a fake clock for unit testing, not to extend stdlib time methods. If the stdlib added a `Sleep(ctx, duration)` method, that would be a candidate for inclusion.

**Comment by ash2k** [comment]
@liggitt ok. Would it be fine to add a function rather than a method? It's short and maybe it's not worth it, but also this snipped will possibly be copied many times.

```go
func SleepInterruptibly(ctx context.Context, clock Clock, d time.Duration) bool {
	t := clock.NewTimer(d)
	select {
	case <-ctx.Done():
		t.Stop()
		return false
	case <-t.C():
		return true
	}
}
```

**Comment by liggitt** [comment]
that seems short/not worth it to me, but I'm happy to hear other perspectives from apimachinery folks

**Comment by MikeSpreitzer** [comment]
Part of this issue is about stuff that was addressed in the other clock package in https://github.com/kubernetes/kubernetes/pull/61976 (as noted in https://github.com/kubernetes/kubernetes/issues/94738).
I would like to consolidate on one clock package.
I agree with adding new methods and deprecating the old ones.
