### ISSUE TITLE
github CI flows do not run on all PRs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/utils#218]
**What happened**:

PRs from new contributors do not auto-start github action CI flows, and PRs do not block on those flows

**What you expected to happen**:

The unit test and apidiff CI actions must pass before merge

**How to reproduce it**:

Seen in https://github.com/kubernetes/utils/pull/216 and https://github.com/kubernetes/utils/pull/215 which merged without apidiff / unit tests running

/assign @dims @thockin

**Comment by dims** [comment]
switched from #2 to #1 below:

![image](https://user-images.githubusercontent.com/23304/130271963-0744d880-daba-4131-abb3-adbf986db596.png)

**Comment by liggitt** [comment]
can we also make the apidiff flow required to merge?

**Comment by thockin** [comment]
I added apidiff to the list of required checks.
