### ISSUE TITLE
make clock support AfterFunc()  

### ISSUE THREAD

**Issue by jonyhy96** [kubernetes/utils#222]
[kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/scheduler/timed_workers.go#L25) still using `k8s.io/apimachinery/pkg/util/clock` because of clock does't implements AfterFunc yet.

We could implement `AfterFunc` in clock and replace `k8s.io/apimachinery/pkg/util/clock` with `k8s.io/utils/clock` in main repository.

**Comment by jonyhy96** [comment]
already resolving by #221

**Comment by MadhavJivrajani** [comment]
/close
duplicate of upstream issue: https://github.com/kubernetes/kubernetes/issues/105173
