### ISSUE TITLE
IntervalClock should be deprecated in favor of SimpleIntervalClock

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/utils#230]
**What happened**:
I noticed that most of the methods of IntervalClock do a `panic`.

**What you expected to happen**:
I expected a supported and recommended type to not be full of methods that have no real implementation.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@MadhavJivrajani 
@kubernetes/sig-api-machinery-bugs

**Comment by MadhavJivrajani** [comment]
/cc @fedebongio @wojtek-t @jpbetz 
(since the `sig-api-machinery-bugs` gh team consists only of `@lavalamp`)

**Comment by MadhavJivrajani** [comment]
@MikeSpreitzer 👋🏼 
I agree we need to deprecate this and remove it eventually. 
The removal here will not be a backward-compatible change (there is an api-diff test that will block) which in this case could be overridden (?):
I checked the current occurrences of `IntervalClock`: https://grep.app/search?q=IntervalClock&case=true&filter[lang][0]=Go
and it looks like no one really uses it for injection purposes and it occurs only as part of vendor dirs or copied-over clock code.
