### ISSUE TITLE
ebtables: Fails to get ebtables version

### ISSUE THREAD

**Issue by defo89** [kubernetes/utils#236]
**What happened**:
Kubelet fails to get `ebtables` version. Apparently some versions do not contain `v` before the version number.

```
# ebtables --version
ebtables 1.8.7 (nf_tables)
```

```
kubelet-wrapper[3583]: I0128 10:17:28.917365    3583 kubenet_linux.go:765] "Failed to get ebtables version. Skip syncing ebtables dedup rules" err="no ebtables version found in string: ebtables 1.8.3 (nf_tables)\n"
```

**What you expected to happen**:
[versionMatcher](https://github.com/kubernetes/utils/blob/master/net/ebtables/ebtables.go#L124) should account for it.

**How to reproduce it**:
I reused the code snippet.

```
package main

import (
	"fmt"
	"regexp"
)

func getEbtablesVersionString(version string) (string, error) {
	versionMatcher := regexp.MustCompile(`v([0-9]+\.[0-9]+\.[0-9]+)`)
	match := versionMatcher.FindStringSubmatch(version)
	if match == nil {
		return "", fmt.Errorf("no ebtables version found in string: %s", version)
	}
	return match[1], nil
}

func main() {
	//version := "ebtables v2.0.10-4 (December 2011)"
	version := "ebtables 1.8.7 (nf_tables)"
	fmt.Printf(getEbtablesVersionString(version))
}
```

If `version := "ebtables 1.8.7 (nf_tables)"` then check fails
```
› ./main
%!(EXTRA *errors.errorString=no ebtables version found in string: ebtables 1.8.7 (nf_tables))
```

If `version := "ebtables v2.0.10-4 (December 2011)"`, it goes through.
```
› ./main
2.0.10%!(EXTRA <nil>)
```

**Anything else we need to know?**:
Issue does not occur on Flatcar 2905.2.3 5.10.61-flatcar as the version string is "compliant" :) 
```
$ ebtables --version
ebtables v2.0.10-4 (December 2011)
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release): Flatcar Container Linux by Kinvolk 3033.2.0
- Kernel (e.g. `uname -a`): 5.10.84-flatcar
- Install tools:
- Others:

**Comment by defo89** [comment]
I would also appreciate if someone could help me to understand how bad it is if we have these errors in production ^^

**Comment by aojea** [comment]
> kubenet_linux.go:765]

kubenet has been deprecated recently, it really depends on how `Flatcar Container Linux by Kinvolk 3033.2.0`  works, if it is using kubenet, maybe is a better question for that project

**Comment by thockin** [comment]
The linked PR seems abandoned, if someone wants to take this over.

**Comment by Ab-hishek** [comment]
I can work on it.

**Comment by thockin** [comment]
While we can fix this, it's worth noting that since dockershim was removed, our use of ebtables is gone.

```
$ git grep ebtables | grep -v CHANGELOG
cmd/kubeadm/app/preflight/checks.go:                    InPathCheck{executable: "ebtables", mandatory: false, exec: execer},
test/e2e_node/system/specs/gke.yaml:- name: ebtables
```

And both of those should PROBABLY be re-evaluated

**Comment by thockin** [comment]
@Ab-hishek are you active on this?  If not, we should unassign it and let someone else grab it.

**Comment by Ab-hishek** [comment]
@thockin PR has been raised and is review pending. I thought that we were not gonna take this from your previous comment. None the less, PR is ready for review.
