### ISSUE TITLE
Feature request: Tagged releases

### ISSUE THREAD

**Issue by lucacome** [kubernetes/utils#273]
**Is your feature request related to a problem? Please describe.**

We use dependabot to keep our dependencies up to date and it seems like it's struggling with dependencies that don't have tags/releases.

**Describe the solution you'd like in detail**

Create tags and releases for this project.

**Describe alternatives you've considered**

Manually updating this dependency in all the projects.

**Comment by Sijoma** [comment]
I +1. this.

**Comment by liggitt** [comment]
I'm not in favor of adding tagging / release maintenance to this repo. Essentially we would be tagging a new release after ~every merge, which would still bump dependencies.
