### ISSUE TITLE
FakeExec is missing CommandContext

### ISSUE THREAD

**Issue by owainlewis** [kubernetes/utils#30]
The FakeExec struct is missing an implementation of the CommandContext method which was added in this PR **https://github.com/kubernetes/utils/pull/27**

```go
func (fake *FakeExec) CommandContext(ctx context.Context, cmd string, args ...string) exec.Cmd {
}
```

**Comment by mengqiy** [comment]
@anfernee

**Comment by anfernee** [comment]
didn't notice that, pr on the way.
