### ISSUE TITLE
move kubernetes/kubernetes/tree/master/pkg/util/keymutex into utils

### ISSUE THREAD

**Issue by pohly** [kubernetes/utils#62]
ceph-csi pulls https://github.com/kubernetes/kubernetes/tree/master/pkg/util/keymutex from kubernetes/kubernetes (https://github.com/ceph/ceph-csi/tree/master/vendor/k8s.io/kubernetes/pkg/util/keymutex) and now I would also like to use it in another CSI driver. The code itself is simple at first glance and might not cross the "complex enough to be worth vendoring" threshold, but it has had at least one bug in the past (https://github.com/kubernetes/kubernetes/issues/65113). Sharing future maintenance in k8s.io/utils probably is better than other projects manually copying the code or vendoring kubernetes/kubernetes.

I discussed it with @msau42 on Slack (https://kubernetes.slack.com/conversation/C09R23FHP/p1544112842053400) and we agreed that it is worthwhile to ask here. If you agree that it is acceptable for k8s.io/utils, then I will proceed with preparing a PR.

**Comment by thockin** [comment]
NB that the implementation was changed to a hashed mutex (easier to clean
up).

https://github.com/kubernetes/utils/pull/55 proposed moving it to utils,
but it got closed - not sure why.
