### ISSUE TITLE
Need tests for trace package

### ISSUE THREAD

**Issue by dims** [kubernetes/utils#69]
please see comment in https://github.com/kubernetes/utils/pull/65#issuecomment-456990325

**Comment by ashishranjan738** [comment]
I am working on it

**Comment by ashishranjan738** [comment]
@dims can you assign me this issue i would like to work on it

**Comment by dims** [comment]
@ashishranjan738 just go ahead, it's a fresh issue no one is working on it

**Comment by dims** [comment]
see main kubernetes repository on how this code is used for inspiration for the test cases

**Comment by ashishranjan738** [comment]
sure thanks
