### ISSUE TITLE
integer.RoundToInt32 fails for 0.49999999999999994

### ISSUE THREAD

**Issue by matiasanaya** [kubernetes/utils#71]
If you add the following test to `integer/integer_test.go`:

```
{
  num: 0.49999999999999994,
  exp: 0,
}
```

And then run the tests, they fail:

```
go test ./integer
--- FAIL: TestRoundToInt32 (0.00s)
	integer_test.go:243: executing scenario 0
	integer_test.go:243: executing scenario 1
	integer_test.go:243: executing scenario 2
	integer_test.go:243: executing scenario 3
	integer_test.go:243: executing scenario 4
	integer_test.go:243: executing scenario 5
	integer_test.go:245: expected 0, got 1
	integer_test.go:243: executing scenario 6
FAIL
FAIL	github.com/kubernetes/utils/integer	0.006s
```

Is this beyond the scope of this function? If not I can submit a PR to fix this, though would it be acceptable to use `math.Round` provided in Go 1.10 and above?

**Comment by thockin** [comment]
If math.Round now offers the same or better behavior, it's fine to switch
to that.

**Comment by matiasanaya** [comment]
I meant use `math.Round` within `integer.RoundToInt32` to fix it. `math.Round` does not provide the same behaviour because it returns a `float64`.

A fix for this issue could look like:

```
// RoundToInt32 rounds floats into integer numbers.
func RoundToInt32(a float64) int32 {
	a = math.Round(a)
	if a < 0 {
		return int32(a - 0.1)
	}
	return int32(a + 0.1)
}
```

**Comment by thockin** [comment]
NOt sure why adding/subtracting 0.1?

**Comment by matiasanaya** [comment]
I assumed that an `int32` represented as a `float64` could be inaccurate in certain cases. After reading up a bit, I understand that adding/subtracting `0.1` is useless.

So this would be enough:

```
// RoundToInt32 rounds floats into integer numbers.
func RoundToInt32(a float64) int32 { return int32(math.Round(a)) }
```

Thoughts?

**Comment by thockin** [comment]
And I like the test case you found, let's add it :)

**Comment by sk-** [comment]
@thockin are there any plans to fix this? I see the affected code has not been changed since this issue was opened.
