### ISSUE TITLE
Move apimachinery/pkg/util/diff to utils

### ISSUE THREAD

**Issue by rajathagasthya** [kubernetes/utils#75]
We use that package in unit tests for some of our operators to generate diffs between actual and expected CR objects. If you think it's a good idea to add it to this repo, I'm happy to help!

**Comment by thockin** [comment]
No objections, but note that the bar is higher in this rpo for code
quality, API, and testing.  You might get the opportunity to fix APis on
the way in.

**Comment by rajathagasthya** [comment]
This is actually already implemented in #82. So I'll close this. Thanks.
